// <auto-generated />
using System;
using MattEland.Jaimes.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MattEland.Jaimes.Repositories.Migrations
{
    [DbContext(typeof(JaimesDbContext))]
    [Migration("20251215033002_UpdateSeedDataForScenariosAndPlayers")]
    partial class UpdateSeedDataForScenariosAndPlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.ChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreviousHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThreadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("MessageId");

                    b.HasIndex("PreviousHistoryId");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.CrackedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CrackedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessedChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("RelativeDirectory")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("CrackedDocuments");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.DocumentChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChunkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector");

                    b.Property<string>("QdrantPointId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId")
                        .IsUnique();

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.DocumentMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("DocumentMetadata");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MostRecentHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MostRecentHistoryId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RulesetId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ChatHistoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatHistoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = "emcee",
                            Description = "Default player",
                            Name = "Emcee",
                            RulesetId = "dnd5e"
                        },
                        new
                        {
                            Id = "kigorath",
                            Description = "A towering goliath druid who communes with the primal spirits of stone and storm. Their skin is marked with tribal patterns that glow faintly when channeling nature magic.",
                            Name = "Kigorath the Goliath Druid",
                            RulesetId = "dnd5e"
                        },
                        new
                        {
                            Id = "glim",
                            Description = "A small frog wizard with bright, curious eyes and a penchant for collecting strange spell components. They speak in a croaky voice and are always eager to learn new magic.",
                            Name = "Glim the Frog Wizard",
                            RulesetId = "dnd5e"
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilterJson")
                        .HasColumnType("text");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RulesetId");

                    b.ToTable("RagSearchQueries");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchResultChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RagSearchQueryId")
                        .HasColumnType("uuid");

                    b.Property<double>("Relevancy")
                        .HasColumnType("double precision");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId");

                    b.HasIndex("RagSearchQueryId");

                    b.HasIndex("Relevancy");

                    b.ToTable("RagSearchResultChunks");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Ruleset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rulesets");

                    b.HasData(
                        new
                        {
                            Id = "dnd5e",
                            Name = "Dungeons and Dragons 5th Edition"
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("InitialGreeting")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UPDATE ME");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = "islandTest",
                            Description = "Island test scenario",
                            InitialGreeting = "You wake on a white sand beach, waves lapping at your boots. Jungle drums echo from the treeline ahead, and your scattered gear lies within reach. What do you do?",
                            Name = "Island Test",
                            RulesetId = "dnd5e",
                            SystemPrompt = "You are a Dungeon Master running a solo D&D 5th Edition adventure on a mysterious tropical island. Use D&D 5e rules for combat and skill checks. CRITICAL GUIDELINES: Keep every response to ONE short paragraph maximum—be concise and easy to read. NEVER assume the player's actions, feelings, or decisions; only describe what the player observes. End each response with a simple prompt like 'What do you do?' to let the player drive the action. You may use markdown bold (**text**) and italic (*text*) but never use headers."
                        },
                        new
                        {
                            Id = "codemashKalahari",
                            Description = "A whimsical fantasy adventure set in a LEGO-themed conference center",
                            InitialGreeting = "Welcome to CodeMash! The Kalahari Resort stretches before you, but something is wonderfully strange—everything is made of LEGO bricks. Colorful minifigures bustle past carrying tiny laptops, and the waterpark slides gleam in bright plastic hues. Tell me about your character: who are you and what kind of adventure do you seek?",
                            Name = "CodeMash Kalahari: The LEGO Realm",
                            RulesetId = "dnd5e",
                            SystemPrompt = "You are a Dungeon Master running a solo D&D 5th Edition adventure set at the Kalahari Resort in Sandusky, Ohio during the CodeMash conference. Strange magic has transformed the entire resort into a whimsical LEGO-themed fantasy realm where everything is made of colorful bricks. Draw inspiration from LEGO sets and themes when describing the world. The player has stepped from reality into this fantastical brick world. CRITICAL GUIDELINES: Keep every response to ONE short paragraph maximum—be concise and easy to read. NEVER assume the player's actions, feelings, or decisions; only describe what the player observes. End each response with a simple prompt like 'What do you do?' to let the player drive the action. You may use markdown bold (**text**) and italic (*text*) but never use headers."
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.ChatHistory", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "PreviousHistory")
                        .WithMany()
                        .HasForeignKey("PreviousHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Game");

                    b.Navigation("Message");

                    b.Navigation("PreviousHistory");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.DocumentChunk", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.CrackedDocument", "CrackedDocument")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrackedDocument");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "MostRecentHistory")
                        .WithMany()
                        .HasForeignKey("MostRecentHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Player", "Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Games")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Scenario", "Scenario")
                        .WithMany("Games")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MostRecentHistory");

                    b.Navigation("Player");

                    b.Navigation("Ruleset");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Message", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "ChatHistory")
                        .WithMany()
                        .HasForeignKey("ChatHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Game", "Game")
                        .WithMany("Messages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("ChatHistory");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Players")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchResultChunk", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.RagSearchQuery", "RagSearchQuery")
                        .WithMany("ResultChunks")
                        .HasForeignKey("RagSearchQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RagSearchQuery");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Scenarios")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchQuery", b =>
                {
                    b.Navigation("ResultChunks");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Ruleset", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");

                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
