// <auto-generated />
using System;
using MattEland.Jaimes.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MattEland.Jaimes.Repositories.Migrations
{
    [DbContext(typeof(JaimesDbContext))]
    [Migration("20251116194813_SwitchToSqlite")]
    partial class SwitchToSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.ChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PreviousHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("MessageId");

                    b.HasIndex("PreviousHistoryId");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MostRecentHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MostRecentHistoryId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RulesetId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ChatHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatHistoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = "emcee",
                            Description = "Default player",
                            Name = "Emcee",
                            RulesetId = "dnd5e"
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Ruleset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rulesets");

                    b.HasData(
                        new
                        {
                            Id = "dnd5e",
                            Name = "Dungeons and Dragons 5th Edition"
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewGameInstructions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UPDATE ME");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UPDATE ME");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = "islandTest",
                            Description = "Island test scenario",
                            Name = "Island Test",
                            NewGameInstructions = "You find yourself washed ashore on a pristine tropical beach. The warm sun beats down on your skin as you take in your surroundings. Crystal-clear turquoise water laps gently at the white sand beach. Behind you, a dense jungle stretches inland, filled with the sounds of exotic birds and rustling leaves. Your gear is scattered nearby, having survived the shipwreck that brought you here. You have no memory of how you arrived, but you know one thing: you must survive and discover the secrets of this mysterious island. What do you do first?",
                            RulesetId = "dnd5e",
                            SystemPrompt = "You are a Dungeon Master running a solo D&D 5th Edition adventure. You guide a single player through an engaging narrative on a mysterious tropical island. Create vivid descriptions, present interesting choices, and adapt the story based on the player's actions. Use D&D 5e rules for combat, skill checks, and character interactions. Keep the adventure challenging but fair, and always maintain an immersive atmosphere. When formatting your responses, you may use markdown for bold (**text**) and italic (*text*) formatting, but do not use markdown headers (lines starting with #). Write naturally in paragraph form without section headers."
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.ChatHistory", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "PreviousHistory")
                        .WithMany()
                        .HasForeignKey("PreviousHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Game");

                    b.Navigation("Message");

                    b.Navigation("PreviousHistory");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "MostRecentHistory")
                        .WithMany()
                        .HasForeignKey("MostRecentHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Player", "Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Games")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Scenario", "Scenario")
                        .WithMany("Games")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MostRecentHistory");

                    b.Navigation("Player");

                    b.Navigation("Ruleset");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Message", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "ChatHistory")
                        .WithMany()
                        .HasForeignKey("ChatHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Game", "Game")
                        .WithMany("Messages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("ChatHistory");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Players")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Scenarios")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Ruleset", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");

                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
