// <auto-generated />
using System;
using MattEland.Jaimes.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MattEland.Jaimes.Repositories.Migrations
{
    [DbContext(typeof(JaimesDbContext))]
    [Migration("20251214215600_RemoveNewGameInstructionsFromScenario")]
    partial class RemoveNewGameInstructionsFromScenario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.ChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreviousHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThreadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("MessageId");

                    b.HasIndex("PreviousHistoryId");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.CrackedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CrackedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessedChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("RelativeDirectory")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("CrackedDocuments");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.DocumentChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChunkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector");

                    b.Property<string>("QdrantPointId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId")
                        .IsUnique();

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.DocumentMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("DocumentMetadata");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MostRecentHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MostRecentHistoryId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RulesetId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ChatHistoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatHistoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = "emcee",
                            Description = "Default player",
                            Name = "Emcee",
                            RulesetId = "dnd5e"
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilterJson")
                        .HasColumnType("text");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RulesetId");

                    b.ToTable("RagSearchQueries");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchResultChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RagSearchQueryId")
                        .HasColumnType("uuid");

                    b.Property<double>("Relevancy")
                        .HasColumnType("double precision");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId");

                    b.HasIndex("RagSearchQueryId");

                    b.HasIndex("Relevancy");

                    b.ToTable("RagSearchResultChunks");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Ruleset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rulesets");

                    b.HasData(
                        new
                        {
                            Id = "dnd5e",
                            Name = "Dungeons and Dragons 5th Edition"
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("InitialGreeting")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UPDATE ME");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = "islandTest",
                            Description = "Island test scenario",
                            InitialGreeting = "You find yourself washed ashore on a pristine tropical beach. The warm sun beats down on your skin as you take in your surroundings. Crystal-clear turquoise water laps gently at the white sand beach. Behind you, a dense jungle stretches inland, filled with the sounds of exotic birds and rustling leaves. Your gear is scattered nearby, having survived the shipwreck that brought you here. You have no memory of how you arrived, but you know one thing: you must survive and discover the secrets of this mysterious island. What do you do first?",
                            Name = "Island Test",
                            RulesetId = "dnd5e",
                            SystemPrompt = "You are a Dungeon Master running a solo D&D 5th Edition adventure. You guide a single player through an engaging narrative on a mysterious tropical island. Create vivid descriptions, present interesting choices, and adapt the story based on the player's actions. Use D&D 5e rules for combat, skill checks, and character interactions. Keep the adventure challenging but fair, and always maintain an immersive atmosphere. When formatting your responses, you may use markdown for bold (**text**) and italic (*text*) formatting, but do not use markdown headers (lines starting with #). Write naturally in paragraph form without section headers."
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.ChatHistory", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "PreviousHistory")
                        .WithMany()
                        .HasForeignKey("PreviousHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Game");

                    b.Navigation("Message");

                    b.Navigation("PreviousHistory");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.DocumentChunk", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.CrackedDocument", "CrackedDocument")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrackedDocument");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "MostRecentHistory")
                        .WithMany()
                        .HasForeignKey("MostRecentHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Player", "Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Games")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Scenario", "Scenario")
                        .WithMany("Games")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MostRecentHistory");

                    b.Navigation("Player");

                    b.Navigation("Ruleset");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Message", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "ChatHistory")
                        .WithMany()
                        .HasForeignKey("ChatHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Game", "Game")
                        .WithMany("Messages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("ChatHistory");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Players")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchResultChunk", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.RagSearchQuery", "RagSearchQuery")
                        .WithMany("ResultChunks")
                        .HasForeignKey("RagSearchQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RagSearchQuery");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Scenarios")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchQuery", b =>
                {
                    b.Navigation("ResultChunks");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Ruleset", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");

                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
