// <auto-generated />
using System;
using MattEland.Jaimes.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MattEland.Jaimes.Repositories.Migrations
{
    [DbContext(typeof(JaimesDbContext))]
    partial class JaimesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.AgentInstructionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModelId")
                        .HasColumnType("integer");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("AgentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("AgentInstructionVersions");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.ChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreviousHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThreadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("MessageId");

                    b.HasIndex("PreviousHistoryId");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.CrackedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CrackedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessedChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("RelativeDirectory")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("CrackedDocuments");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.DocumentChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChunkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector");

                    b.Property<string>("QdrantPointId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId")
                        .IsUnique();

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.DocumentMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("DocumentMetadata");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.EvaluationExecution", b =>
                {
                    b.Property<string>("ExecutionName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExecutionName");

                    b.ToTable("EvaluationExecutions");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.EvaluationScenarioIteration", b =>
                {
                    b.Property<string>("ExecutionName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ScenarioName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("IterationName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ExecutionName", "ScenarioName", "IterationName");

                    b.ToTable("EvaluationScenarioIterations");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Evaluator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Evaluators");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InstructionVersionId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MostRecentHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("InstructionVersionId");

                    b.HasIndex("MostRecentHistoryId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RulesetId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameLower")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComputedColumnSql("LOWER(\"Name\")", true);

                    b.Property<string>("StorytellerNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "NameLower")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.LocationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationEvents");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ChatHistoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("InstructionVersionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsScriptedMessage")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int?>("NextMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<int?>("PreviousMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ChatHistoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("InstructionVersionId");

                    b.HasIndex("ModelId");

                    b.HasIndex("NextMessageId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PreviousMessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.MessageEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EmbeddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<string>("QdrantPointId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("MessageEmbeddings");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.MessageEvaluationMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Diagnostics")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EvaluationModelId")
                        .HasColumnType("integer");

                    b.Property<int?>("EvaluatorId")
                        .HasColumnType("integer");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedAt");

                    b.HasIndex("EvaluationModelId");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("MessageId");

                    b.HasIndex("MetricName");

                    b.ToTable("MessageEvaluationMetrics");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.MessageFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InstructionVersionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("boolean");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstructionVersionId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("MessageFeedbacks");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.MessageSentiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<int>("Sentiment")
                        .HasColumnType("integer");

                    b.Property<int>("SentimentSource")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("MessageSentiments");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.MessageToolCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputJson")
                        .HasColumnType("text");

                    b.Property<int?>("InstructionVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<string>("OutputJson")
                        .HasColumnType("text");

                    b.Property<int?>("ToolId")
                        .HasColumnType("integer");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("InstructionVersionId");

                    b.HasIndex("MessageId");

                    b.HasIndex("ToolId");

                    b.ToTable("MessageToolCalls");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Provider", "Endpoint")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Name", "Provider", "Endpoint"), false);

                    b.ToTable("Models");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.NearbyLocation", b =>
                {
                    b.Property<int>("SourceLocationId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Distance")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StorytellerNotes")
                        .HasColumnType("text");

                    b.Property<string>("TravelNotes")
                        .HasColumnType("text");

                    b.HasKey("SourceLocationId", "TargetLocationId");

                    b.HasIndex("TargetLocationId");

                    b.ToTable("NearbyLocations");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = "emcee",
                            Description = "Default player",
                            Name = "Emcee",
                            RulesetId = "dnd5e"
                        },
                        new
                        {
                            Id = "kigorath",
                            Description = "A towering goliath druid who communes with the primal spirits of stone and storm. Their skin is marked with tribal patterns that glow faintly when channeling nature magic.",
                            Name = "Kigorath the Goliath Druid",
                            RulesetId = "dnd5e"
                        },
                        new
                        {
                            Id = "glim",
                            Description = "A small frog wizard with bright, curious eyes and a penchant for collecting strange spell components. They speak in a croaky voice and are always eager to learn new magic.",
                            Name = "Glim the Frog Wizard",
                            RulesetId = "dnd5e"
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilterJson")
                        .HasColumnType("text");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RulesetId");

                    b.ToTable("RagSearchQueries");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchResultChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RagSearchQueryId")
                        .HasColumnType("uuid");

                    b.Property<double>("Relevancy")
                        .HasColumnType("double precision");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId");

                    b.HasIndex("RagSearchQueryId");

                    b.HasIndex("Relevancy");

                    b.ToTable("RagSearchResultChunks");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Ruleset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rulesets");

                    b.HasData(
                        new
                        {
                            Id = "dnd5e",
                            Name = "Dungeons and Dragons 5th Edition"
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("InitialGreeting")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScenarioInstructions")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = "islandTest",
                            Description = "Island test scenario",
                            InitialGreeting = "You wake on a white sand beach, waves lapping at your boots. Jungle drums echo from the treeline ahead, and your scattered gear lies within reach. What do you do?",
                            Name = "Island Test",
                            RulesetId = "dnd5e",
                            ScenarioInstructions = "This tropical island scenario features mysterious jungles, ancient ruins, and hidden dangers. The atmosphere is one of discovery and survival - players encounter exotic wildlife, tribal inhabitants, and forgotten treasures. Maintain a sense of wonder and exploration while keeping the tone adventurous and slightly perilous. The island has a rich history of shipwrecks, pirate legends, and ancient civilizations."
                        },
                        new
                        {
                            Id = "codemashKalahari",
                            Description = "A whimsical fantasy adventure set in a LEGO-themed conference center",
                            InitialGreeting = "Welcome to CodeMash! The Kalahari Resort stretches before you, but something is wonderfully strange—everything is made of LEGO bricks. Colorful minifigures bustle past carrying tiny laptops, and the waterpark slides gleam in bright plastic hues. Tell me about your character: who are you and what kind of adventure do you seek?",
                            Name = "CodeMash Kalahari: The LEGO Realm",
                            RulesetId = "dnd5e",
                            ScenarioInstructions = "The entire Kalahari Resort has been magically transformed into a LEGO-themed fantasy realm. Everything is made of colorful bricks - buildings, furniture, even the people are minifigures. Conference attendees have become adventurers on quests involving programming puzzles, LEGO building challenges, and whimsical brick-based combat. The tone is lighthearted and creative, with opportunities for clever problem-solving and LEGO-inspired humor. Players can build, rebuild, and explore this vibrant, colorful world."
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.ScenarioAgent", b =>
                {
                    b.Property<string>("ScenarioId")
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .HasColumnType("text");

                    b.Property<int?>("InstructionVersionId")
                        .HasColumnType("integer");

                    b.HasKey("ScenarioId", "AgentId");

                    b.HasIndex("AgentId");

                    b.HasIndex("InstructionVersionId");

                    b.ToTable("ScenarioAgents");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.AgentInstructionVersion", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Agent", "Agent")
                        .WithMany("InstructionVersions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Model", "Model")
                        .WithMany("AgentInstructionVersions")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Agent");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.ChatHistory", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "PreviousHistory")
                        .WithMany()
                        .HasForeignKey("PreviousHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Game");

                    b.Navigation("Message");

                    b.Navigation("PreviousHistory");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.DocumentChunk", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.CrackedDocument", "CrackedDocument")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrackedDocument");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.EvaluationScenarioIteration", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.EvaluationExecution", "Execution")
                        .WithMany("ScenarioIterations")
                        .HasForeignKey("ExecutionName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.AgentInstructionVersion", "InstructionVersion")
                        .WithMany()
                        .HasForeignKey("InstructionVersionId");

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "MostRecentHistory")
                        .WithMany()
                        .HasForeignKey("MostRecentHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Player", "Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Games")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Scenario", "Scenario")
                        .WithMany("Games")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("InstructionVersion");

                    b.Navigation("MostRecentHistory");

                    b.Navigation("Player");

                    b.Navigation("Ruleset");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Location", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.LocationEvent", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Message", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Agent", "Agent")
                        .WithMany("Messages")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.ChatHistory", "ChatHistory")
                        .WithMany()
                        .HasForeignKey("ChatHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Game", "Game")
                        .WithMany("Messages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.AgentInstructionVersion", "InstructionVersion")
                        .WithMany("Messages")
                        .HasForeignKey("InstructionVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Model", "Model")
                        .WithMany("Messages")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Message", "NextMessage")
                        .WithMany()
                        .HasForeignKey("NextMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Message", "PreviousMessage")
                        .WithMany()
                        .HasForeignKey("PreviousMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Agent");

                    b.Navigation("ChatHistory");

                    b.Navigation("Game");

                    b.Navigation("InstructionVersion");

                    b.Navigation("Model");

                    b.Navigation("NextMessage");

                    b.Navigation("Player");

                    b.Navigation("PreviousMessage");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.MessageEmbedding", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Message", "Message")
                        .WithOne("MessageEmbedding")
                        .HasForeignKey("MattEland.Jaimes.Repositories.Entities.MessageEmbedding", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.MessageEvaluationMetric", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Model", "EvaluationModel")
                        .WithMany("EvaluationMetrics")
                        .HasForeignKey("EvaluationModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Evaluator", "Evaluator")
                        .WithMany("EvaluationMetrics")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationModel");

                    b.Navigation("Evaluator");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.MessageFeedback", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.AgentInstructionVersion", "InstructionVersion")
                        .WithMany()
                        .HasForeignKey("InstructionVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructionVersion");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.MessageSentiment", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Message", "Message")
                        .WithOne("MessageSentiment")
                        .HasForeignKey("MattEland.Jaimes.Repositories.Entities.MessageSentiment", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.MessageToolCall", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.AgentInstructionVersion", "InstructionVersion")
                        .WithMany()
                        .HasForeignKey("InstructionVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Message", "Message")
                        .WithMany("ToolCalls")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Tool", "Tool")
                        .WithMany("ToolCalls")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InstructionVersion");

                    b.Navigation("Message");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.NearbyLocation", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Location", "SourceLocation")
                        .WithMany("NearbyLocationsAsSource")
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Location", "TargetLocation")
                        .WithMany("NearbyLocationsAsTarget")
                        .HasForeignKey("TargetLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceLocation");

                    b.Navigation("TargetLocation");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Players")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchResultChunk", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.RagSearchQuery", "RagSearchQuery")
                        .WithMany("ResultChunks")
                        .HasForeignKey("RagSearchQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RagSearchQuery");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Scenarios")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.ScenarioAgent", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Agent", "Agent")
                        .WithMany("ScenarioAgents")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.AgentInstructionVersion", "InstructionVersion")
                        .WithMany("ScenarioAgents")
                        .HasForeignKey("InstructionVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Scenario", "Scenario")
                        .WithMany("ScenarioAgents")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("InstructionVersion");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Agent", b =>
                {
                    b.Navigation("InstructionVersions");

                    b.Navigation("Messages");

                    b.Navigation("ScenarioAgents");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.AgentInstructionVersion", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("ScenarioAgents");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.EvaluationExecution", b =>
                {
                    b.Navigation("ScenarioIterations");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Evaluator", b =>
                {
                    b.Navigation("EvaluationMetrics");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Location", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("NearbyLocationsAsSource");

                    b.Navigation("NearbyLocationsAsTarget");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Message", b =>
                {
                    b.Navigation("MessageEmbedding");

                    b.Navigation("MessageSentiment");

                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Model", b =>
                {
                    b.Navigation("AgentInstructionVersions");

                    b.Navigation("EvaluationMetrics");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.RagSearchQuery", b =>
                {
                    b.Navigation("ResultChunks");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Ruleset", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");

                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("ScenarioAgents");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Tool", b =>
                {
                    b.Navigation("ToolCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
