// <auto-generated />
using System;
using MattEland.Jaimes.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MattEland.Jaimes.Repositories.Migrations
{
    [DbContext(typeof(JaimesDbContext))]
    partial class JaimesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RulesetId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = "emcee",
                            Description = "Default player",
                            RulesetId = "dnd5e"
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Ruleset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rulesets");

                    b.HasData(
                        new
                        {
                            Id = "dnd5e",
                            Name = "Dungeons and Dragons 5th Edition"
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = "islandTest",
                            Description = "Island test scenario",
                            RulesetId = "dnd5e"
                        });
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Player", "Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Games")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Scenario", "Scenario")
                        .WithMany("Games")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Ruleset");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Message", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Game", "Game")
                        .WithMany("Messages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Players")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.HasOne("MattEland.Jaimes.Repositories.Entities.Ruleset", "Ruleset")
                        .WithMany("Scenarios")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Game", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Player", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Ruleset", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");

                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("MattEland.Jaimes.Repositories.Entities.Scenario", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
