@ApiService_HostAddress = http://localhost:5532

### Start a new Game
POST {{ApiService_HostAddress}}/games/
Content-Type: application/json

{
  "rulesetId": "dnd5e",
  "scenarioId": "islandTest",
  "playerId": "emcee"
}

### GET All Active Games
GET {{ApiService_HostAddress}}/games/
Accept: application/json

### Get the specific game
GET {{ApiService_HostAddress}}/games/6e613ac2-c898-464d-8b45-9b1a3410cc8f
Content-Type: application/json
