@ApiService_HostAddress = http://localhost:5532

### Start a new Game
POST {{ApiService_HostAddress}}/games/
Content-Type: application/json

{
  "rulesetId": "dnd5e",
  "scenarioId": "islandTest",
  "playerId": "emcee"
}

### GET All Active Games
GET {{ApiService_HostAddress}}/games/
Accept: application/json

### Get the specific game
GET {{ApiService_HostAddress}}/games/d23436d7-1525-43ec-9a99-9f43458d9a54
Content-Type: application/json
