namespace MattEland.Jaimes.Repositories.Entities;

/// <summary>
/// Stores the results of running a test case against a specific agent version.
/// </summary>
public class TestCaseRun
{
    public int Id { get; set; }

    public int TestCaseId { get; set; }
    public TestCase? TestCase { get; set; }

    public required string AgentId { get; set; }
    public Agent? Agent { get; set; }

    public int InstructionVersionId { get; set; }
    public AgentInstructionVersion? InstructionVersion { get; set; }

    public DateTime ExecutedAt { get; set; }

    /// <summary>
    /// The response generated by the agent during this test run.
    /// </summary>
    public required string GeneratedResponse { get; set; }

    /// <summary>
    /// Duration of the agent invocation in milliseconds.
    /// </summary>
    public int? DurationMs { get; set; }

    /// <summary>
    /// Links this run to an EvaluationExecution for HTML report generation.
    /// </summary>
    [MaxLength(250)]
    public string? ExecutionName { get; set; }

    /// <summary>
    /// Reference to the stored HTML report file.
    /// </summary>
    public int? ReportFileId { get; set; }

    public StoredFile? ReportFile { get; set; }

    // Navigation properties
    public ICollection<TestCaseRunMetric> Metrics { get; set; } = [];
}
